service:
  name: catordog

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  region: europe-west1 # OPTIONAL: Edit if you want

  # THESE TWO MUST BE UPDATED BY YOU!
  project: "" # EDIT THIS to your value
  credentials: ~/.gcloud/{KEYFILE}.json # EDIT THIS to your value

  runtime: nodejs10
  memorySize: 1024
  timeout: 10s

functions:
  catOrDog:
    handler: catOrDog
    events:
      - http: catOrDog
        method: POST
